---
language: node_js
node_js:
- 0.8
notifications:
  webhooks:
    urls:
      secure: "DyE+oAQ47xEi/XCkFwGM8y0aMx+O9Phddpb04sSJL3OZX52X5+qk2VfVLtuv\nRpYsAKxf/CWnc2XDXEJ+Mvtckov+d/eELNtcyplDiwak3bVBsS85IvddlS0x\n7a2KRRkErjwP81dveB6DUCAQUXQo+DLIvxixmB0i4lCcr4tqaTk="
    on_succes: always
    on_failure: always
    on_start: true
